CREATE TABLE [dbo].[Member]
(
	[Id_Member] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[Pseudo] NVARCHAR(50) NOT NULL,
	[Email] NVARCHAR(250) NOT NULL,
	[Password] BINARY(64) NOT NULL,
	[Salt] NVARCHAR(100) NOT NULL,

	CONSTRAINT PK_Member PRIMARY KEY([Id_Member]),
	CONSTRAINT UK_Pseudo UNIQUE([Pseudo]),
	CONSTRAINT UK_Email UNIQUE([Email])
)
