CREATE TABLE [dbo].[Message]
(
	[Id_Message] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(), 
	[Content] NVARCHAR(4000) NOT NULL,
	[Submit_Date] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[Update_Date] DATETIME2 NULL,
	[Id_Topic] UNIQUEIDENTIFIER NOT NULL,
	[Id_Member] UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT PK_Message PRIMARY KEY ([Id_Message]),
	CONSTRAINT FK_Message_Member FOREIGN KEY([Id_Member])
		REFERENCES [Member]([Id_Member]),
	CONSTRAINT FK_Message_Topic FOREIGN KEY([Id_Topic])
		REFERENCES [Topic]([Id_Topic])
)
