CREATE TABLE [dbo].[Topic]
(
	[Id_Topic] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[Title] NVARCHAR(50) NOT NULL,
	[Id_Creator] UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT PK_Topic PRIMARY KEY([Id_Topic]),
	CONSTRAINT FK_Topic_Creator FOREIGN KEY([Id_creator])
		REFERENCES [Member]([Id_Member])
)
